apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-news
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-news
  template:
    metadata:
      labels:
        app: kube-news
    spec:
      containers:
        - name: app
          image: ghcr.io/emanuelfrn/kube-news:v1
          ports:
            - containerPort: 8080
          env:
            - name: DB_DATABASE
              value: kubenews
            - name: DB_USERNAME
              value: kubenews
            - name: DB_PASSWORD
              value: '123'
            - name: DB_HOST
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: kube-news
spec:
  type: LoadBalancer
  selector:
    app: kube-news
  ports:
    - port: 80
      targetPort: 8080